url: 'https://qooba.github.io'
name: qooba.net
description: 'Coding, Technology, Machine Learning, Architecture'
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag

theme: jekyll-theme-slate
