# Dependencies
markdown:         redcarpet
highlighter:      pygments

# Permalinks
#permalink:        pretty
#relative_permalinks: true

# Setup
name:             blog.qooba.net
title:            Qooba
tagline:          'Qooba blog'
description:      'Coding, Technology, Machine Learning, Architecture'
url:              https://blog.qooba.net
baseurl:          /
relative_url:     /

author:
  name:           'Qooba'
  url:            https://blog.qooba.net/about

paginate:         5

# Custom vars
version:          2.1.0

github:
  repo:           https://github.com/qooba

plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag

# defaults:
#   -
#     scope:
#       path: "" # an empty string here means all files in the project
#     values:
#       layout: "default"

#theme: jekyll-theme-slate
#theme: minimal-mistakes-jekyll
