url: 'https://qooba.github.io'
name: qooba.net
description: 'Coding, Technology, Machine Learning, Architecture'
plugins:
  - jekyll-gist
  - jekyll-coffeescript
  - jekyll-seo-tag

defaults:
  -
    scope:
      path: "" # an empty string here means all files in the project
    values:
      layout: "default"

#theme: jekyll-theme-slate
#theme: minimal-mistakes-jekyll
